#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Script para refatorar page_tradicao.py de 6 tabs para 3 tabs
Baseado no mesmo padrão usado em page_drogarias.py
"""

def refactor_tradicao_to_3_tabs():
    # Ler arquivo backup
    with open('streamlit_conciliacao/page_tradicao_backup.py', 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    print(f"Arquivo original: {len(lines)} linhas")
    
    # Nova versão limpa
    result = []
    
    # Parte 1: Tudo até antes das tabs (linhas 1-129)
    result.extend(lines[0:129])
    print(f"✓ Cabeçalho copiado: linhas 1-129")
    
    # Parte 2: Nova definição de 3 tabs
    result.append('    tabs = st.tabs(["🏠 Processo", "📊 Resultados", "⚙️ Avançado"])\n')
    result.append('\n')
    result.append('    # ====== TAB 0: PROCESSO ======\n')
    print(f"✓ Definição das 3 tabs adicionada")
    
    # Parte 3: Manter tabs[0] original (Upload) - linhas 135-333
    result.extend(lines[134:333])
    print(f"✓ Tab 0 (Processo) copiada: linhas 135-333")
    
    # Remover o `else:` vazio se existir (verificar contexto)
    # Procurar pelo padrão try/except/else e remover else vazio
    if result[-1].strip() == 'else:':
        result.pop()
        print("✓ Removido 'else:' vazio")
    elif result[-2].strip().startswith('else:'):
        # Remover linhas do else vazio
        while result[-1].strip() in ['', 'else:', '# ====== PRE-VISUALIZACAO ======']:
            result.pop()
        print("✓ Removido bloco 'else:' vazio")
    
    # Parte 4: Adicionar tabs[1] e tabs[2] com funcionalidade completa
    
    # TAB 1: RESULTADOS
    result.append('\n')
    result.append('    # ====== TAB 1: RESULTADOS ======\n')
    result.append('    with tabs[1]:\n')
    result.append('        if "trad_matches" in st.session_state:\n')
    result.append('            matches = st.session_state["trad_matches"]\n')
    result.append('            pend_data = st.session_state["trad_pend_data"]\n')
    result.append('            cols_pag = st.session_state["trad_cols_pag"]\n')
    result.append('            cols_ext = st.session_state["trad_cols_ext"]\n')
    result.append('\n')
    result.append('            # Dashboard de métricas\n')
    result.append('            stats = pend_data.get("stats", {})\n')
    result.append('            st.subheader("📊 Dashboard de Conciliação")\n')
    result.append('            \n')
    result.append('            col1, col2, col3, col4 = st.columns(4)\n')
    result.append('            with col1:\n')
    result.append('                st.metric("✓ Conciliados", stats.get("matches", 0))\n')
    result.append('            with col2:\n')
    result.append('                st.metric("📄 Total Pagamentos", stats.get("total_pagamentos", 0))\n')
    result.append('            with col3:\n')
    result.append('                st.metric("💳 Saídas Extrato", stats.get("total_saidas", 0))\n')
    result.append('            with col4:\n')
    result.append('                pct = stats.get("pct_conciliacao", 0)\n')
    result.append('                st.metric("🎯 Taxa Conciliação", f"{pct:.1f}%")\n')
    result.append('\n')
    result.append('            st.divider()\n')
    result.append('\n')
    result.append('            # Grupos conciliados\n')
    result.append('            st.subheader("✓ Grupos Conciliados")\n')
    result.append('            if not matches.empty:\n')
    result.append('                st.dataframe(matches, use_container_width=True, height=300)\n')
    result.append('            else:\n')
    result.append('                st.info("Nenhum match encontrado")\n')
    result.append('\n')
    result.append('            st.divider()\n')
    result.append('\n')
    result.append('            # Pendências lado a lado\n')
    result.append('            col1, col2 = st.columns(2)\n')
    result.append('            with col1:\n')
    result.append('                st.subheader(f"⏳ Pagamentos Pendentes: {len(pend_data[\'unmatched_pagamentos\'])}")\n')
    result.append('                if not pend_data["unmatched_pagamentos"].empty:\n')
    result.append('                    st.dataframe(\n')
    result.append('                        pend_data["unmatched_pagamentos"][["_data", "_valor", cols_pag["fornecedor"]]],\n')
    result.append('                        use_container_width=True,\n')
    result.append('                        height=300\n')
    result.append('                    )\n')
    result.append('                else:\n')
    result.append('                    st.success("Todos os pagamentos foram conciliados!")\n')
    result.append('\n')
    result.append('            with col2:\n')
    result.append('                st.subheader(f"❓ Saídas sem Pagamento: {len(pend_data[\'unmatched_extrato\'])}")\n')
    result.append('                if not pend_data["unmatched_extrato"].empty:\n')
    result.append('                    st.dataframe(\n')
    result.append('                        pend_data["unmatched_extrato"][["_data", "_valor", cols_ext["historico"]]],\n')
    result.append('                        use_container_width=True,\n')
    result.append('                        height=300\n')
    result.append('                    )\n')
    result.append('                else:\n')
    result.append('                    st.success("Todas as saídas foram identificadas!")\n')
    result.append('\n')
    result.append('            st.divider()\n')
    result.append('\n')
    result.append('            # Análise de qualidade\n')
    result.append('            st.subheader("📈 Análise de Qualidade")\n')
    result.append('            pct_conciliacao = stats.get("pct_conciliacao", 0)\n')
    result.append('            \n')
    result.append('            if pct_conciliacao >= 95:\n')
    result.append('                st.success(f"✓ **Excelente**: Taxa de conciliação de {pct_conciliacao:.1f}%")\n')
    result.append('                st.caption("A maioria dos lançamentos foram conciliados com sucesso.")\n')
    result.append('            elif pct_conciliacao >= 85:\n')
    result.append('                st.warning(f"⚠ **Bom**: Taxa de conciliação de {pct_conciliacao:.1f}%")\n')
    result.append('                st.caption("Há algumas pendências que merecem atenção.")\n')
    result.append('            else:\n')
    result.append('                st.error(f"✗ **Crítico**: Taxa de apenas {pct_conciliacao:.1f}%")\n')
    result.append('                st.caption("Muitos lançamentos não foram conciliados. Revise os dados.")\n')
    result.append('                \n')
    result.append('        else:\n')
    result.append('            st.info("📁 Faça upload de todos os arquivos e clique em **PROCESSAR** na aba Processo para ver os resultados.")\n')
    result.append('\n')
    
    # TAB 2: AVANÇADO
    result.append('    # ====== TAB 2: AVANÇADO ======\n')
    result.append('    with tabs[2]:\n')
    result.append('        if "trad_df_pag" in st.session_state:\n')
    result.append('            st.header("⚙️ Configurações Avançadas")\n')
    result.append('            \n')
    result.append('            # Validações de Cadastros\n')
    result.append('            if "trad_validation_result" in st.session_state:\n')
    result.append('                validation_result = st.session_state["trad_validation_result"]\n')
    result.append('                \n')
    result.append('                st.subheader("🔍 Validação de Cadastros")\n')
    result.append('                \n')
    result.append('                if validation_result and validation_result.get("tem_bloqueadores"):\n')
    result.append('                    st.error("⚠️ **PROBLEMAS DETECTADOS** - Corrija antes de exportar")\n')
    result.append('                    \n')
    result.append('                    if validation_result.get("fornecedores_faltantes"):\n')
    result.append('                        with st.expander(\n')
    result.append('                            f"❌ Fornecedores sem Conta ({len(validation_result[\'fornecedores_faltantes\'])})",\n')
    result.append('                            expanded=True\n')
    result.append('                        ):\n')
    result.append('                            for forn in validation_result["fornecedores_faltantes"]:\n')
    result.append('                                st.warning(f"• {forn}")\n')
    result.append('                    \n')
    result.append('                    if validation_result.get("clientes_faltantes"):\n')
    result.append('                        with st.expander(\n')
    result.append('                            f"❌ Clientes sem Conta ({len(validation_result[\'clientes_faltantes\'])})",\n')
    result.append('                            expanded=True\n')
    result.append('                        ):\n')
    result.append('                            for cli in validation_result["clientes_faltantes"]:\n')
    result.append('                                st.warning(f"• {cli}")\n')
    result.append('                    \n')
    result.append('                    if validation_result.get("contas_especiais_faltantes"):\n')
    result.append('                        with st.expander(\n')
    result.append('                            f"❌ Contas Especiais Faltantes ({len(validation_result[\'contas_especiais_faltantes\'])})",\n')
    result.append('                            expanded=True\n')
    result.append('                        ):\n')
    result.append('                            for conta in validation_result["contas_especiais_faltantes"]:\n')
    result.append('                                st.error(f"• {conta}")\n')
    result.append('                else:\n')
    result.append('                    st.success("✓ Todas as validações passaram!")\n')
    result.append('            \n')
    result.append('            st.divider()\n')
    result.append('            \n')
    result.append('            # Pré-visualização expandida dos dados\n')
    result.append('            st.subheader("📋 Pré-visualização dos Dados")\n')
    result.append('            \n')
    result.append('            if "trad_df_pag" in st.session_state:\n')
    result.append('                with st.expander("💳 Pagamentos (completo)", expanded=False):\n')
    result.append('                    df_pag = st.session_state["trad_df_pag"]\n')
    result.append('                    st.dataframe(df_pag, use_container_width=True, height=400)\n')
    result.append('                    st.caption(f"Total: {len(df_pag)} registros")\n')
    result.append('            \n')
    result.append('            if "trad_df_ext_saidas" in st.session_state:\n')
    result.append('                with st.expander("📤 Extrato - Saídas (completo)", expanded=False):\n')
    result.append('                    df_saidas = st.session_state["trad_df_ext_saidas"]\n')
    result.append('                    st.dataframe(df_saidas, use_container_width=True, height=400)\n')
    result.append('                    st.caption(f"Total: {len(df_saidas)} registros")\n')
    result.append('            \n')
    result.append('            if "trad_df_ext_entradas" in st.session_state:\n')
    result.append('                with st.expander("📥 Extrato - Entradas (completo)", expanded=False):\n')
    result.append('                    df_entradas = st.session_state["trad_df_ext_entradas"]\n')
    result.append('                    st.dataframe(df_entradas, use_container_width=True, height=400)\n')
    result.append('                    st.caption(f"Total: {len(df_entradas)} registros")\n')
    result.append('                    \n')
    result.append('                    if not df_entradas.empty:\n')
    result.append('                        from io import BytesIO\n')
    result.append('                        buf = BytesIO()\n')
    result.append('                        df_entradas.to_csv(buf, index=False, sep=";", encoding="utf-8-sig")\n')
    result.append('                        st.download_button(\n')
    result.append('                            "⬇️ Baixar Entradas CSV",\n')
    result.append('                            data=buf.getvalue(),\n')
    result.append('                            file_name="entradas_extrato.csv",\n')
    result.append('                            mime="text/csv"\n')
    result.append('                        )\n')
    result.append('            \n')
    result.append('            if "trad_df_contas" in st.session_state:\n')
    result.append('                with st.expander("📊 Plano de Contas (completo)", expanded=False):\n')
    result.append('                    df_contas = st.session_state["trad_df_contas"]\n')
    result.append('                    st.dataframe(df_contas, use_container_width=True, height=400)\n')
    result.append('                    st.caption(f"Total: {len(df_contas)} contas")\n')
    result.append('                    \n')
    result.append('        else:\n')
    result.append('            st.info("📁 Faça upload de todos os arquivos na aba **Processo** para acessar configurações avançadas.")\n')
    
    # Escrever arquivo limpo
    with open('streamlit_conciliacao/page_tradicao.py', 'w', encoding='utf-8') as f:
        f.writelines(result)
    
    print(f"\n✅ REFATORAÇÃO CONCLUÍDA")
    print(f"   Original: {len(lines)} linhas")
    print(f"   Refatorado: {len(result)} linhas")
    print(f"   Redução: {len(lines) - len(result)} linhas")
    print(f"\n📋 Estrutura:")
    print(f"   - 3 tabs: Processo, Resultados, Avançado")
    print(f"   - Tab 0: Upload e processamento")
    print(f"   - Tab 1: Dashboard completo de resultados")
    print(f"   - Tab 2: Validações e previews expandidos")

if __name__ == "__main__":
    refactor_tradicao_to_3_tabs()
